<?xml version="1.0" encoding="utf-8"?><Database Name="MailsAndSenders" Class="EmailsSenderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MailsAndSenders;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="MailSender_Pattern_MVVM.Properties.Settings" SettingsPropertyName="MailsAndSendersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmailSender" Member="EmailSenders">
    <Type Name="EmailSender">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>